project_name: bwtui
gomod:
  proxy: true
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    main: ./cmd/bwtui
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
      - '^(refactor|chore|docs|build):'
